### ISSUE TITLE
misc_register Return 

### ISSUE THREAD

**Issue by staroooooolove** [rwana1753/linux-driver-tm1637#1]
/*

old
	ret = misc_register(&tm1637_misc);
	if (!ret) {
		goto fail;
	}
new
	ret = misc_register(&tm1637_misc);
	if (ret) {
		goto fail;
	}root
	
*/

**Comment by rwana1753** [comment]
As you said,
if the registration is successful, the function returns zero.

Thank you for finding my mistake.
